#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZTn.Droid.D3Calculator.Resource", IsApplication=true)]

namespace ZTn.Droid.D3Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::ZTn.Droid.D3Calculator.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::ZTn.Droid.D3Calculator.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barbarian_female = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int barbarian_male = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int crusader_female = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int crusader_male = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int demonhunter_female = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int demonhunter_male = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_add = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_send = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int monk_female = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int monk_male = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int witchdoctor_female = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int witchdoctor_male = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int wizard_female = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int wizard_male = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
