//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTn.Pcl.D3Calculator.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZTn.Pcl.D3Calculator.Resources.Lang", typeof(Lang).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your account information.
        /// </summary>
        internal static string AccountEditorTitle {
            get {
                return ResourceManager.GetString("AccountEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcane resist.
        /// </summary>
        internal static string ArcaneResist {
            get {
                return ResourceManager.GetString("ArcaneResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack speed.
        /// </summary>
        internal static string AttackSpeed {
            get {
                return ResourceManager.GetString("AttackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        internal static string Barbarian {
            get {
                return ResourceManager.GetString("Barbarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Tag.
        /// </summary>
        internal static string BattleTag {
            get {
                return ResourceManager.GetString("BattleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonuses.
        /// </summary>
        internal static string Bonuses {
            get {
                return ResourceManager.GetString("Bonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        internal static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo 3 Careers.
        /// </summary>
        internal static string Careers {
            get {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold resist.
        /// </summary>
        internal static string ColdResist {
            get {
                return ResourceManager.GetString("ColdResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critic chance.
        /// </summary>
        internal static string CriticChance {
            get {
                return ResourceManager.GetString("CriticChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critic damage.
        /// </summary>
        internal static string CriticDamage {
            get {
                return ResourceManager.GetString("CriticDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crusader.
        /// </summary>
        internal static string Crusader {
            get {
                return ResourceManager.GetString("Crusader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damages.
        /// </summary>
        internal static string Damages {
            get {
                return ResourceManager.GetString("Damages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon Hunter.
        /// </summary>
        internal static string DemonHunter {
            get {
                return ResourceManager.GetString("DemonHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        internal static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elites.
        /// </summary>
        internal static string Elites {
            get {
                return ResourceManager.GetString("Elites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire resist.
        /// </summary>
        internal static string FireResist {
            get {
                return ResourceManager.GetString("FireResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoldFind.
        /// </summary>
        internal static string GoldFind {
            get {
                return ResourceManager.GetString("GoldFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild name.
        /// </summary>
        internal static string GuildName {
            get {
                return ResourceManager.GetString("GuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore.
        /// </summary>
        internal static string Hardcore {
            get {
                return ResourceManager.GetString("Hardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore monsters.
        /// </summary>
        internal static string HardcoreMonsters {
            get {
                return ResourceManager.GetString("HardcoreMonsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        internal static string Healing {
            get {
                return ResourceManager.GetString("Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero.
        /// </summary>
        internal static string Hero {
            get {
                return ResourceManager.GetString("Hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string HeroClass {
            get {
                return ResourceManager.GetString("HeroClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        internal static string Heroes {
            get {
                return ResourceManager.GetString("Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game server.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracers.
        /// </summary>
        internal static string ItemBracers {
            get {
                return ResourceManager.GetString("ItemBracers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string ItemFeet {
            get {
                return ResourceManager.GetString("ItemFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        internal static string ItemHands {
            get {
                return ResourceManager.GetString("ItemHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string ItemHead {
            get {
                return ResourceManager.GetString("ItemHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left finger.
        /// </summary>
        internal static string ItemLeftFinger {
            get {
                return ResourceManager.GetString("ItemLeftFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string ItemLegs {
            get {
                return ResourceManager.GetString("ItemLegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main hand.
        /// </summary>
        internal static string ItemMainHand {
            get {
                return ResourceManager.GetString("ItemMainHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string ItemNeck {
            get {
                return ResourceManager.GetString("ItemNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off hand.
        /// </summary>
        internal static string ItemOffHand {
            get {
                return ResourceManager.GetString("ItemOffHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right finger.
        /// </summary>
        internal static string ItemRightFinger {
            get {
                return ResourceManager.GetString("ItemRightFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders.
        /// </summary>
        internal static string ItemShoulders {
            get {
                return ResourceManager.GetString("ItemShoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torso.
        /// </summary>
        internal static string ItemTorso {
            get {
                return ResourceManager.GetString("ItemTorso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string ItemWaist {
            get {
                return ResourceManager.GetString("ItemWaist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry.
        /// </summary>
        internal static string Jewelry {
            get {
                return ResourceManager.GetString("Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills lifetime.
        /// </summary>
        internal static string KillsLifetime {
            get {
                return ResourceManager.GetString("KillsLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life.
        /// </summary>
        internal static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life on hit.
        /// </summary>
        internal static string LifeOnHit {
            get {
                return ResourceManager.GetString("LifeOnHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life per kill.
        /// </summary>
        internal static string LifePerKill {
            get {
                return ResourceManager.GetString("LifePerKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life steal.
        /// </summary>
        internal static string LifeSteal {
            get {
                return ResourceManager.GetString("LifeSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning resist.
        /// </summary>
        internal static string LightningResist {
            get {
                return ResourceManager.GetString("LightningResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Career.
        /// </summary>
        internal static string LoadingCareer {
            get {
                return ResourceManager.GetString("LoadingCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Hero.
        /// </summary>
        internal static string LoadingHero {
            get {
                return ResourceManager.GetString("LoadingHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagicFind.
        /// </summary>
        internal static string MagicFind {
            get {
                return ResourceManager.GetString("MagicFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        internal static string Monk {
            get {
                return ResourceManager.GetString("Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsters.
        /// </summary>
        internal static string Monsters {
            get {
                return ResourceManager.GetString("Monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon.
        /// </summary>
        internal static string ParagonLevel {
            get {
                return ResourceManager.GetString("ParagonLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon level hardcore.
        /// </summary>
        internal static string ParagonLevelHardcore {
            get {
                return ResourceManager.GetString("ParagonLevelHardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon level season.
        /// </summary>
        internal static string ParagonLevelSeason {
            get {
                return ResourceManager.GetString("ParagonLevelSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon level season hardcore.
        /// </summary>
        internal static string ParagonLevelSeasonHardcore {
            get {
                return ResourceManager.GetString("ParagonLevelSeasonHardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        internal static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical resist.
        /// </summary>
        internal static string PhysicalResist {
            get {
                return ResourceManager.GetString("PhysicalResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison resist.
        /// </summary>
        internal static string PoisonResist {
            get {
                return ResourceManager.GetString("PoisonResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary resource.
        /// </summary>
        internal static string PrimaryResource {
            get {
                return ResourceManager.GetString("PrimaryResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary resource.
        /// </summary>
        internal static string SecondaryResource {
            get {
                return ResourceManager.GetString("SecondaryResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toughness.
        /// </summary>
        internal static string Toughness {
            get {
                return ResourceManager.GetString("Toughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch Doctor.
        /// </summary>
        internal static string WitchDoctor {
            get {
                return ResourceManager.GetString("WitchDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        internal static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
    }
}
