#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZTnDroid.D3Calculator.Resource", IsApplication=true)]

namespace ZTnDroid.D3Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int blueItem = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int greenItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int orangeItem = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int rune_textcolor = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int yellowItem = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barbarian_female = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int barbarian_male = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int demonhunter_female = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int demonhunter_male = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monk_female = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monk_male = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int witchdoctor_female = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int witchdoctor_male = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int wizard_female = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int wizard_male = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001c
			public const int AccountsListView = 2131165212;
			
			// aapt resource value: 0x7f07002b
			public const int AddNewAccount = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int DeleteContent = 2131165230;
			
			// aapt resource value: 0x7f070026
			public const int HeroesListView = 2131165222;
			
			// aapt resource value: 0x7f070020
			public const int Pager = 2131165216;
			
			// aapt resource value: 0x7f07002d
			public const int RefreshContent = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int Settings = 2131165228;
			
			// aapt resource value: 0x7f07002a
			public const int SubmitNewAccount = 2131165226;
			
			// aapt resource value: 0x7f070021
			public const int Title = 2131165217;
			
			// aapt resource value: 0x7f070004
			public const int attributeName = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int attributeValue = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int battleTagEditText = 2131165185;
			
			// aapt resource value: 0x7f07001b
			public const int divider = 2131165211;
			
			// aapt resource value: 0x7f070006
			public const int fragment_container = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int gearItemArmor = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int gearItemArmorLayout = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int gearItemAttacksPerSecond = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int gearItemAttacksPerSecondLayout = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int gearItemDamageLayout = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int gearItemDamageMax = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int gearItemDamageMin = 2131165196;
			
			// aapt resource value: 0x7f070012
			public const int gearItemDescription = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int gearItemDps = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int gearItemDpsLayout = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int gearItemName = 2131165192;
			
			// aapt resource value: 0x7f070018
			public const int heroClass = 2131165208;
			
			// aapt resource value: 0x7f070028
			public const int heroGearListView = 2131165224;
			
			// aapt resource value: 0x7f070019
			public const int heroHardcore = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int heroLastUpdated = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int heroLevel = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int heroName = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int heroParagon = 2131165206;
			
			// aapt resource value: 0x7f070029
			public const int heroSkillsListView = 2131165225;
			
			// aapt resource value: 0x7f070027
			public const int heroStatsListView = 2131165223;
			
			// aapt resource value: 0x7f070003
			public const int hostSpinner = 2131165187;
			
			// aapt resource value: 0x7f070013
			public const int imageClass = 2131165203;
			
			// aapt resource value: 0x7f070007
			public const int imageGearItem = 2131165191;
			
			// aapt resource value: 0x7f070022
			public const int imageSkill = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int killsLifetimeListView = 2131165221;
			
			// aapt resource value: 0x7f07001e
			public const int runeDescription = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int runeName = 2131165213;
			
			// aapt resource value: 0x7f07001a
			public const int sectionLabel = 2131165210;
			
			// aapt resource value: 0x7f07001f
			public const int settingOnline = 2131165215;
			
			// aapt resource value: 0x7f070024
			public const int skillDescription = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int skillName = 2131165219;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNewAccount = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AttributeListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentContainer = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GearItemListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HeroesListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Home = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RuneListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SectionHeaderListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Settings = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SimpleViewPager = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SkillListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ViewCareer = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ViewHero = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ViewHeroGear = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ViewHeroSkills = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int AddNewAccountActivity = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int HomeActivity = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Settings = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ViewCareerActivity = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ViewHeroActivity = 2131099652;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int Add = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int AddNewAccount = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int AddNewAccountActivityLabel = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int ApplicationName = 2131034119;
			
			// aapt resource value: 0x7f050029
			public const int Armor = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int AttacksPerSecond = 2131034154;
			
			// aapt resource value: 0x7f050021
			public const int BattleTag = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int BattleTagExample = 2131034146;
			
			// aapt resource value: 0x7f050008
			public const int Cancel = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Careers = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Characteristics = 2131034122;
			
			// aapt resource value: 0x7f05002c
			public const int DamagePerSecond = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int Damages = 2131034155;
			
			// aapt resource value: 0x7f05000b
			public const int DeleteContent = 2131034123;
			
			// aapt resource value: 0x7f05004a
			public const int EHP_DPS = 2131034186;
			
			// aapt resource value: 0x7f05001c
			public const int ErrorOccuredWhileRetrievingData = 2131034140;
			
			// aapt resource value: 0x7f05000c
			public const int FetchCareer = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int Heroes = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int HomeActivityLabel = 2131034112;
			
			// aapt resource value: 0x7f050023
			public const int Host = 2131034147;
			
			// aapt resource value: 0x7f05000e
			public const int KilledElites = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int KilledHardcore = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int KilledMonsters = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int KillsLifetime = 2131034132;
			
			// aapt resource value: 0x7f050020
			public const int Language = 2131034144;
			
			// aapt resource value: 0x7f050016
			public const int Loading = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int LoadingCareer = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int LoadingHero = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int LoadingIcons = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int LoadingItems = 2131034138;
			
			// aapt resource value: 0x7f05001f
			public const int OnlineMode = 2131034143;
			
			// aapt resource value: 0x7f050012
			public const int Progress = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int RefreshContent = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int Settings = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int SettingsActivityLabel = 2131034114;
			
			// aapt resource value: 0x7f050030
			public const int Socket = 2131034160;
			
			// aapt resource value: 0x7f050015
			public const int SubmitNewAccount = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int ViewCareerActivityLabel = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ViewHeroActivityLabel = 2131034116;
			
			// aapt resource value: 0x7f05001b
			public const int WaitWhileRetrievingData = 2131034139;
			
			// aapt resource value: 0x7f05004e
			public const int arcaneResist = 2131034190;
			
			// aapt resource value: 0x7f05004c
			public const int armor = 2131034188;
			
			// aapt resource value: 0x7f050042
			public const int attackSpeed = 2131034178;
			
			// aapt resource value: 0x7f050038
			public const int attributes = 2131034168;
			
			// aapt resource value: 0x7f050024
			public const int barbarian = 2131034148;
			
			// aapt resource value: 0x7f050057
			public const int bonuses = 2131034199;
			
			// aapt resource value: 0x7f05004f
			public const int coldResist = 2131034191;
			
			// aapt resource value: 0x7f05001e
			public const int computed = 2131034142;
			
			// aapt resource value: 0x7f050040
			public const int criticChance = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int criticDamage = 2131034177;
			
			// aapt resource value: 0x7f05003f
			public const int damage = 2131034175;
			
			// aapt resource value: 0x7f05002d
			public const int damagePerSecond = 2131034157;
			
			// aapt resource value: 0x7f05003e
			public const int damages = 2131034174;
			
			// aapt resource value: 0x7f05004b
			public const int defense = 2131034187;
			
			// aapt resource value: 0x7f050025
			public const int demonHunter = 2131034149;
			
			// aapt resource value: 0x7f05001d
			public const int details = 2131034141;
			
			// aapt resource value: 0x7f050039
			public const int dexterity = 2131034169;
			
			// aapt resource value: 0x7f05004d
			public const int dodge = 2131034189;
			
			// aapt resource value: 0x7f050049
			public const int effectiveHitpoints = 2131034185;
			
			// aapt resource value: 0x7f05003d
			public const int elites = 2131034173;
			
			// aapt resource value: 0x7f050050
			public const int fireResist = 2131034192;
			
			// aapt resource value: 0x7f05002e
			public const int gear = 2131034158;
			
			// aapt resource value: 0x7f050058
			public const int goldFind = 2131034200;
			
			// aapt resource value: 0x7f050035
			public const int heroClass = 2131034165;
			
			// aapt resource value: 0x7f05003a
			public const int intelligence = 2131034170;
			
			// aapt resource value: 0x7f050060
			public const int itemBracers = 2131034208;
			
			// aapt resource value: 0x7f05005c
			public const int itemFeet = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int itemHands = 2131034205;
			
			// aapt resource value: 0x7f05005a
			public const int itemHead = 2131034202;
			
			// aapt resource value: 0x7f050065
			public const int itemLeftFinger = 2131034213;
			
			// aapt resource value: 0x7f05005f
			public const int itemLegs = 2131034207;
			
			// aapt resource value: 0x7f050061
			public const int itemMainHand = 2131034209;
			
			// aapt resource value: 0x7f050066
			public const int itemNeck = 2131034214;
			
			// aapt resource value: 0x7f050062
			public const int itemOffHand = 2131034210;
			
			// aapt resource value: 0x7f050064
			public const int itemRightFinger = 2131034212;
			
			// aapt resource value: 0x7f05005e
			public const int itemShoulders = 2131034206;
			
			// aapt resource value: 0x7f05005b
			public const int itemTorso = 2131034203;
			
			// aapt resource value: 0x7f050063
			public const int itemWaist = 2131034211;
			
			// aapt resource value: 0x7f050034
			public const int lastUpdated = 2131034164;
			
			// aapt resource value: 0x7f050036
			public const int level = 2131034166;
			
			// aapt resource value: 0x7f050043
			public const int life = 2131034179;
			
			// aapt resource value: 0x7f050047
			public const int lifeBonusPerGlobe = 2131034183;
			
			// aapt resource value: 0x7f050044
			public const int lifeOnHit = 2131034180;
			
			// aapt resource value: 0x7f050046
			public const int lifePerKill = 2131034182;
			
			// aapt resource value: 0x7f050048
			public const int lifeRegenPerSecond = 2131034184;
			
			// aapt resource value: 0x7f050045
			public const int lifeSteal = 2131034181;
			
			// aapt resource value: 0x7f050051
			public const int lightningResist = 2131034193;
			
			// aapt resource value: 0x7f050059
			public const int magicFind = 2131034201;
			
			// aapt resource value: 0x7f050026
			public const int monk = 2131034150;
			
			// aapt resource value: 0x7f050037
			public const int paragon = 2131034167;
			
			// aapt resource value: 0x7f050031
			public const int passiveSkill = 2131034161;
			
			// aapt resource value: 0x7f050053
			public const int physicalResist = 2131034195;
			
			// aapt resource value: 0x7f050052
			public const int poisonResist = 2131034194;
			
			// aapt resource value: 0x7f050055
			public const int primaryResource = 2131034197;
			
			// aapt resource value: 0x7f050054
			public const int resources = 2131034196;
			
			// aapt resource value: 0x7f050056
			public const int secondaryResource = 2131034198;
			
			// aapt resource value: 0x7f05002f
			public const int setBonuses = 2131034159;
			
			// aapt resource value: 0x7f050032
			public const int skill = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int skills = 2131034163;
			
			// aapt resource value: 0x7f05003b
			public const int strength = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int vitality = 2131034172;
			
			// aapt resource value: 0x7f050027
			public const int witchDoctor = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int wizard = 2131034152;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
