#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZTnDroid.D3Calculator.Resource", IsApplication=true)]

namespace ZTnDroid.D3Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZTn.Bnet.Portable.Android.Resource.String.ApplicationName = global::ZTnDroid.D3Calculator.Resource.String.ApplicationName;
			global::ZTn.Bnet.Portable.Android.Resource.String.Hello = global::ZTnDroid.D3Calculator.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int blueItem = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int greenItem = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int hardcore_text = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int heroclass_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int herolevel_text = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int heroname_text = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int item_description = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int itemstat_description = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int orangeItem = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int passive_description = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int rune_description = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int rune_text = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int skill_description = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int skill_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int socket_description = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int whiteItem = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int yellowItem = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barbarian_female = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int barbarian_male = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int crusader_female = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int crusader_male = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int demonhunter_female = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int demonhunter_male = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int drawer_shadow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_navigation_drawer = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int monk_female = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int monk_male = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int witchdoctor_female = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int witchdoctor_male = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int wizard_female = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int wizard_male = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070033
			public const int AccountsListView = 2131165235;
			
			// aapt resource value: 0x7f070046
			public const int AddNewAccount = 2131165254;
			
			// aapt resource value: 0x7f070044
			public const int CancelEditedItem = 2131165252;
			
			// aapt resource value: 0x7f070048
			public const int DeleteContent = 2131165256;
			
			// aapt resource value: 0x7f07003f
			public const int HeroesListView = 2131165247;
			
			// aapt resource value: 0x7f070039
			public const int Pager = 2131165241;
			
			// aapt resource value: 0x7f070047
			public const int RefreshContent = 2131165255;
			
			// aapt resource value: 0x7f070045
			public const int SubmitEditedItem = 2131165253;
			
			// aapt resource value: 0x7f070043
			public const int SubmitNewAccount = 2131165251;
			
			// aapt resource value: 0x7f07003a
			public const int Title = 2131165242;
			
			// aapt resource value: 0x7f07000c
			public const int add = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int attributeName = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int attributeValue = 2131165189;
			
			// aapt resource value: 0x7f07001a
			public const int basicValuesLayout = 2131165210;
			
			// aapt resource value: 0x7f070001
			public const int battleTagEditText = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int divider = 2131165195;
			
			// aapt resource value: 0x7f070034
			public const int drawer_layout = 2131165236;
			
			// aapt resource value: 0x7f070017
			public const int editDivider = 2131165207;
			
			// aapt resource value: 0x7f070006
			public const int fragment_container = 2131165190;
			
			// aapt resource value: 0x7f070023
			public const int gearItemArmor = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int gearItemArmorLayout = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int gearItemAttacksPerSecond = 2131165217;
			
			// aapt resource value: 0x7f070020
			public const int gearItemAttacksPerSecondLayout = 2131165216;
			
			// aapt resource value: 0x7f07001d
			public const int gearItemDamageLayout = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int gearItemDamageMax = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int gearItemDamageMin = 2131165214;
			
			// aapt resource value: 0x7f070019
			public const int gearItemDescription = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int gearItemDps = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int gearItemDpsLayout = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int gearItemEdit = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int gearItemName = 2131165192;
			
			// aapt resource value: 0x7f070028
			public const int gearPassiveDescription = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int gearPrimaryDescription = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int gearPrimaryTitle = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int gearSecondaryDescription = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int gearSecondaryTitle = 2131165222;
			
			// aapt resource value: 0x7f070029
			public const int gearSocketsDescription = 2131165225;
			
			// aapt resource value: 0x7f070031
			public const int heroClass = 2131165233;
			
			// aapt resource value: 0x7f070041
			public const int heroGearListView = 2131165249;
			
			// aapt resource value: 0x7f070032
			public const int heroHardcore = 2131165234;
			
			// aapt resource value: 0x7f070030
			public const int heroLastUpdated = 2131165232;
			
			// aapt resource value: 0x7f07002e
			public const int heroLevel = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int heroName = 2131165229;
			
			// aapt resource value: 0x7f07002f
			public const int heroParagon = 2131165231;
			
			// aapt resource value: 0x7f070042
			public const int heroSkillsListView = 2131165250;
			
			// aapt resource value: 0x7f070040
			public const int heroStatsListView = 2131165248;
			
			// aapt resource value: 0x7f070003
			public const int hostSpinner = 2131165187;
			
			// aapt resource value: 0x7f07002c
			public const int imageClass = 2131165228;
			
			// aapt resource value: 0x7f070016
			public const int imageGearItem = 2131165206;
			
			// aapt resource value: 0x7f07003b
			public const int imageSkill = 2131165243;
			
			// aapt resource value: 0x7f07003e
			public const int killsLifetimeListView = 2131165246;
			
			// aapt resource value: 0x7f07000a
			public const int label = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int layoutAttributes = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int layoutDefense = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int layoutItemDamage = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int layoutSkillBonus = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int layoutSockets = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int layoutWeaponDamage = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout = 2131165202;
			
			// aapt resource value: 0x7f070035
			public const int navigation_drawer = 2131165237;
			
			// aapt resource value: 0x7f07002a
			public const int remove = 2131165226;
			
			// aapt resource value: 0x7f070037
			public const int runeDescription = 2131165239;
			
			// aapt resource value: 0x7f070036
			public const int runeName = 2131165238;
			
			// aapt resource value: 0x7f070007
			public const int scrollViewContainer = 2131165191;
			
			// aapt resource value: 0x7f070015
			public const int sectionDivider = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int sectionLabel = 2131165204;
			
			// aapt resource value: 0x7f070038
			public const int settingOnline = 2131165240;
			
			// aapt resource value: 0x7f07003d
			public const int skillDescription = 2131165245;
			
			// aapt resource value: 0x7f07003c
			public const int skillName = 2131165244;
			
			// aapt resource value: 0x7f07002b
			public const int socketLabel = 2131165227;
			
			// aapt resource value: 0x7f070013
			public const int textView = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNewAccount = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AttributeListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentContainer = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GearItemEditor = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GearItemListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GearItemRowEditor = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GearSocketRowEditor = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HeroesListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Home = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NavigationDrawer = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int NavigationDrawerFragmentContainer = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RuneListItem = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SectionHeaderListItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Settings = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SimpleViewPager = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SkillListItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ViewCareer = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ViewHero = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ViewHeroGear = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ViewHeroSkills = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int AddNewAccountActivity = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int GearItemEditorFragment = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int HomeActivity = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ViewCareerActivity = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ViewHeroActivity = 2131099652;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040008
			public const int Add = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int AddNewAccount = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int AddNewAccountActivityLabel = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04002c
			public const int Armor = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int AttacksPerSecond = 2130968621;
			
			// aapt resource value: 0x7f040022
			public const int BattleTag = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int BattleTagExample = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int BattleTags = 2130968612;
			
			// aapt resource value: 0x7f040070
			public const int BonusDamage = 2130968688;
			
			// aapt resource value: 0x7f04000a
			public const int Cancel = 2130968586;
			
			// aapt resource value: 0x7f040016
			public const int CancelEditedItem = 2130968598;
			
			// aapt resource value: 0x7f04000b
			public const int Careers = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Characteristics = 2130968588;
			
			// aapt resource value: 0x7f04002e
			public const int Damages = 2130968622;
			
			// aapt resource value: 0x7f04000d
			public const int DeleteContent = 2130968589;
			
			// aapt resource value: 0x7f040051
			public const int EHP_DPS = 2130968657;
			
			// aapt resource value: 0x7f0400ac
			public const int EditedItem = 2130968748;
			
			// aapt resource value: 0x7f04001d
			public const int ErrorOccuredWhileRetrievingData = 2130968605;
			
			// aapt resource value: 0x7f04000e
			public const int FetchCareer = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int GearItemEditorActivityLabel = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000f
			public const int Heroes = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int HomeActivityLabel = 2130968580;
			
			// aapt resource value: 0x7f040025
			public const int Host = 2130968613;
			
			// aapt resource value: 0x7f0400ae
			public const int ItemEditingCanceled = 2130968750;
			
			// aapt resource value: 0x7f0400ad
			public const int ItemEditingFinished = 2130968749;
			
			// aapt resource value: 0x7f040013
			public const int KillsLifetime = 2130968595;
			
			// aapt resource value: 0x7f040021
			public const int Language = 2130968609;
			
			// aapt resource value: 0x7f040017
			public const int Loading = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int LoadingCareer = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int LoadingHero = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int LoadingIcons = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int LoadingItems = 2130968603;
			
			// aapt resource value: 0x7f040020
			public const int OnlineMode = 2130968608;
			
			// aapt resource value: 0x7f040011
			public const int Progress = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int RefreshContent = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int Settings = 2130968592;
			
			// aapt resource value: 0x7f040005
			public const int SettingsActivityLabel = 2130968581;
			
			// aapt resource value: 0x7f040032
			public const int Socket = 2130968626;
			
			// aapt resource value: 0x7f040015
			public const int SubmitEditedItem = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int SubmitNewAccount = 2130968596;
			
			// aapt resource value: 0x7f040006
			public const int ViewCareerActivityLabel = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ViewHeroActivityLabel = 2130968583;
			
			// aapt resource value: 0x7f04001c
			public const int WaitWhileRetrievingData = 2130968604;
			
			// aapt resource value: 0x7f04006f
			public const int WeaponOnlyDamage = 2130968687;
			
			// aapt resource value: 0x7f040055
			public const int allResists = 2130968661;
			
			// aapt resource value: 0x7f040073
			public const int arcaneMax = 2130968691;
			
			// aapt resource value: 0x7f040081
			public const int arcaneMaxWeapon = 2130968705;
			
			// aapt resource value: 0x7f040072
			public const int arcaneMin = 2130968690;
			
			// aapt resource value: 0x7f040080
			public const int arcaneMinWeapon = 2130968704;
			
			// aapt resource value: 0x7f040056
			public const int arcaneResist = 2130968662;
			
			// aapt resource value: 0x7f040053
			public const int armor = 2130968659;
			
			// aapt resource value: 0x7f040049
			public const int attackSpeed = 2130968649;
			
			// aapt resource value: 0x7f040071
			public const int attacksPerSecond = 2130968689;
			
			// aapt resource value: 0x7f04003d
			public const int attributes = 2130968637;
			
			// aapt resource value: 0x7f040026
			public const int barbarian = 2130968614;
			
			// aapt resource value: 0x7f04005f
			public const int bonuses = 2130968671;
			
			// aapt resource value: 0x7f040075
			public const int coldMax = 2130968693;
			
			// aapt resource value: 0x7f040083
			public const int coldMaxWeapon = 2130968707;
			
			// aapt resource value: 0x7f040074
			public const int coldMin = 2130968692;
			
			// aapt resource value: 0x7f040082
			public const int coldMinWeapon = 2130968706;
			
			// aapt resource value: 0x7f040057
			public const int coldResist = 2130968663;
			
			// aapt resource value: 0x7f04001f
			public const int computed = 2130968607;
			
			// aapt resource value: 0x7f040047
			public const int criticChance = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int criticDamage = 2130968648;
			
			// aapt resource value: 0x7f040027
			public const int crusader = 2130968615;
			
			// aapt resource value: 0x7f040046
			public const int damage = 2130968646;
			
			// aapt resource value: 0x7f0400a4
			public const int damageDealtPercentVsElites_Arcane = 2130968740;
			
			// aapt resource value: 0x7f0400a5
			public const int damageDealtPercentVsElites_Cold = 2130968741;
			
			// aapt resource value: 0x7f0400a6
			public const int damageDealtPercentVsElites_Fire = 2130968742;
			
			// aapt resource value: 0x7f0400a7
			public const int damageDealtPercentVsElites_Holy = 2130968743;
			
			// aapt resource value: 0x7f0400a8
			public const int damageDealtPercentVsElites_Lightning = 2130968744;
			
			// aapt resource value: 0x7f0400a9
			public const int damageDealtPercentVsElites_Physical = 2130968745;
			
			// aapt resource value: 0x7f0400aa
			public const int damageDealtPercentVsElites_Poison = 2130968746;
			
			// aapt resource value: 0x7f04009d
			public const int damageDealtPercent_Arcane = 2130968733;
			
			// aapt resource value: 0x7f04009e
			public const int damageDealtPercent_Cold = 2130968734;
			
			// aapt resource value: 0x7f04009f
			public const int damageDealtPercent_Fire = 2130968735;
			
			// aapt resource value: 0x7f0400a0
			public const int damageDealtPercent_Holy = 2130968736;
			
			// aapt resource value: 0x7f0400a1
			public const int damageDealtPercent_Lightning = 2130968737;
			
			// aapt resource value: 0x7f0400a2
			public const int damageDealtPercent_Physical = 2130968738;
			
			// aapt resource value: 0x7f0400a3
			public const int damageDealtPercent_Poison = 2130968739;
			
			// aapt resource value: 0x7f04002f
			public const int damagePerSecond = 2130968623;
			
			// aapt resource value: 0x7f04009c
			public const int damagePercentBonusVsElites = 2130968732;
			
			// aapt resource value: 0x7f04008e
			public const int damagePercent_Arcane = 2130968718;
			
			// aapt resource value: 0x7f04008f
			public const int damagePercent_Cold = 2130968719;
			
			// aapt resource value: 0x7f040090
			public const int damagePercent_Fire = 2130968720;
			
			// aapt resource value: 0x7f040091
			public const int damagePercent_Holy = 2130968721;
			
			// aapt resource value: 0x7f040092
			public const int damagePercent_Lightning = 2130968722;
			
			// aapt resource value: 0x7f040093
			public const int damagePercent_Physical = 2130968723;
			
			// aapt resource value: 0x7f040094
			public const int damagePercent_Poison = 2130968724;
			
			// aapt resource value: 0x7f040045
			public const int damages = 2130968645;
			
			// aapt resource value: 0x7f040052
			public const int defense = 2130968658;
			
			// aapt resource value: 0x7f040028
			public const int demonHunter = 2130968616;
			
			// aapt resource value: 0x7f04001e
			public const int details = 2130968606;
			
			// aapt resource value: 0x7f04003e
			public const int dexterity = 2130968638;
			
			// aapt resource value: 0x7f040054
			public const int dodge = 2130968660;
			
			// aapt resource value: 0x7f040050
			public const int effectiveHitpoints = 2130968656;
			
			// aapt resource value: 0x7f040042
			public const int elites = 2130968642;
			
			// aapt resource value: 0x7f040077
			public const int fireMax = 2130968695;
			
			// aapt resource value: 0x7f040085
			public const int fireMaxWeapon = 2130968709;
			
			// aapt resource value: 0x7f040076
			public const int fireMin = 2130968694;
			
			// aapt resource value: 0x7f040084
			public const int fireMinWeapon = 2130968708;
			
			// aapt resource value: 0x7f040058
			public const int fireResist = 2130968664;
			
			// aapt resource value: 0x7f040030
			public const int gear = 2130968624;
			
			// aapt resource value: 0x7f040060
			public const int goldFind = 2130968672;
			
			// aapt resource value: 0x7f040039
			public const int heroClass = 2130968633;
			
			// aapt resource value: 0x7f040079
			public const int holyMax = 2130968697;
			
			// aapt resource value: 0x7f040087
			public const int holyMaxWeapon = 2130968711;
			
			// aapt resource value: 0x7f040078
			public const int holyMin = 2130968696;
			
			// aapt resource value: 0x7f040086
			public const int holyMinWeapon = 2130968710;
			
			// aapt resource value: 0x7f04003f
			public const int intelligence = 2130968639;
			
			// aapt resource value: 0x7f040068
			public const int itemBracers = 2130968680;
			
			// aapt resource value: 0x7f040064
			public const int itemFeet = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int itemHands = 2130968677;
			
			// aapt resource value: 0x7f040062
			public const int itemHead = 2130968674;
			
			// aapt resource value: 0x7f04006d
			public const int itemLeftFinger = 2130968685;
			
			// aapt resource value: 0x7f040067
			public const int itemLegs = 2130968679;
			
			// aapt resource value: 0x7f040069
			public const int itemMainHand = 2130968681;
			
			// aapt resource value: 0x7f04006e
			public const int itemNeck = 2130968686;
			
			// aapt resource value: 0x7f04006a
			public const int itemOffHand = 2130968682;
			
			// aapt resource value: 0x7f04006c
			public const int itemRightFinger = 2130968684;
			
			// aapt resource value: 0x7f040066
			public const int itemShoulders = 2130968678;
			
			// aapt resource value: 0x7f040063
			public const int itemTorso = 2130968675;
			
			// aapt resource value: 0x7f04006b
			public const int itemWaist = 2130968683;
			
			// aapt resource value: 0x7f040038
			public const int lastUpdated = 2130968632;
			
			// aapt resource value: 0x7f04003a
			public const int level = 2130968634;
			
			// aapt resource value: 0x7f04004a
			public const int life = 2130968650;
			
			// aapt resource value: 0x7f04004e
			public const int lifeBonusPerGlobe = 2130968654;
			
			// aapt resource value: 0x7f04004b
			public const int lifeOnHit = 2130968651;
			
			// aapt resource value: 0x7f04004d
			public const int lifePerKill = 2130968653;
			
			// aapt resource value: 0x7f04004f
			public const int lifeRegenPerSecond = 2130968655;
			
			// aapt resource value: 0x7f04004c
			public const int lifeSteal = 2130968652;
			
			// aapt resource value: 0x7f04007b
			public const int lightningMax = 2130968699;
			
			// aapt resource value: 0x7f040089
			public const int lightningMaxWeapon = 2130968713;
			
			// aapt resource value: 0x7f04007a
			public const int lightningMin = 2130968698;
			
			// aapt resource value: 0x7f040088
			public const int lightningMinWeapon = 2130968712;
			
			// aapt resource value: 0x7f040059
			public const int lightningResist = 2130968665;
			
			// aapt resource value: 0x7f040061
			public const int magicFind = 2130968673;
			
			// aapt resource value: 0x7f040029
			public const int monk = 2130968617;
			
			// aapt resource value: 0x7f040043
			public const int monsters = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int monstersHardcore = 2130968644;
			
			// aapt resource value: 0x7f04003b
			public const int paragon = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int paragonHardcore = 2130968636;
			
			// aapt resource value: 0x7f040033
			public const int passiveSkill = 2130968627;
			
			// aapt resource value: 0x7f04007d
			public const int physicalMax = 2130968701;
			
			// aapt resource value: 0x7f04008b
			public const int physicalMaxWeapon = 2130968715;
			
			// aapt resource value: 0x7f04007c
			public const int physicalMin = 2130968700;
			
			// aapt resource value: 0x7f04008a
			public const int physicalMinWeapon = 2130968714;
			
			// aapt resource value: 0x7f04005b
			public const int physicalResist = 2130968667;
			
			// aapt resource value: 0x7f04007f
			public const int poisonMax = 2130968703;
			
			// aapt resource value: 0x7f04008d
			public const int poisonMaxWeapon = 2130968717;
			
			// aapt resource value: 0x7f04007e
			public const int poisonMin = 2130968702;
			
			// aapt resource value: 0x7f04008c
			public const int poisonMinWeapon = 2130968716;
			
			// aapt resource value: 0x7f04005a
			public const int poisonResist = 2130968666;
			
			// aapt resource value: 0x7f0400ab
			public const int powerCooldownReductionPercentAll = 2130968747;
			
			// aapt resource value: 0x7f040036
			public const int primary = 2130968630;
			
			// aapt resource value: 0x7f04005d
			public const int primaryResource = 2130968669;
			
			// aapt resource value: 0x7f04005c
			public const int resources = 2130968668;
			
			// aapt resource value: 0x7f040037
			public const int secondary = 2130968631;
			
			// aapt resource value: 0x7f04005e
			public const int secondaryResource = 2130968670;
			
			// aapt resource value: 0x7f040031
			public const int setBonuses = 2130968625;
			
			// aapt resource value: 0x7f040034
			public const int skill = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int skills = 2130968629;
			
			// aapt resource value: 0x7f040040
			public const int strength = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int vitality = 2130968641;
			
			// aapt resource value: 0x7f040095
			public const int weaponPercent_Arcane = 2130968725;
			
			// aapt resource value: 0x7f040096
			public const int weaponPercent_Cold = 2130968726;
			
			// aapt resource value: 0x7f040097
			public const int weaponPercent_Fire = 2130968727;
			
			// aapt resource value: 0x7f040098
			public const int weaponPercent_Holy = 2130968728;
			
			// aapt resource value: 0x7f040099
			public const int weaponPercent_Lightning = 2130968729;
			
			// aapt resource value: 0x7f04009a
			public const int weaponPercent_Physical = 2130968730;
			
			// aapt resource value: 0x7f04009b
			public const int weaponPercent_Poison = 2130968731;
			
			// aapt resource value: 0x7f04002a
			public const int witchDoctor = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int wizard = 2130968619;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
