//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTnDroid.D3Calculator
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int AccountsListView = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int AddNewAccount = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int CareerKilledElites = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int CareerKilledHardcore = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int CareerKilledMonsters = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int HeroesListView = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int RefreshContent = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int SubmitNewAccount = 2131099667;
			
			// aapt resource value: 0x7f060001
			public const int battleTagEditText = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int heroClass = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int heroHardcore = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int heroLevel = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int heroName = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int heroParagon = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int hostSpinner = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int tableLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int tableRow1 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow2 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int tableRow3 = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int textView3 = 2131099660;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNewAccount = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HeroesListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewCareer = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int AddNewAccountActivity = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int HomeActivity = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ViewCareerActivity = 2131034114;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Add = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AddNewAccount = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Cancel = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int FetchCareer = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Heroes = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int KilledElites = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int KilledHardcore = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int KilledMonsters = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int RefreshContent = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Statistics = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int SubmitNewAccount = 2130968587;
			
			private String()
			{
			}
		}
	}
}
